const actionTypes = {
    SET_ACTORS: 'SET_ACTORS',
    SET_SELECTED_YEAR: 'SET_SELECTED_YEAR',
    SET_SELECTED_GENRES: 'SET_SELECTED_GENRES',
    SET_GENRES: 'SET_GENRES',
    SET_LIST_VIEW: 'SET_LIST_VIEW',
    SET_ACTOR: 'SET_ACTOR',
    SET_SEARCH_PHRASE: 'SET_SEARCH_PHRASE',
    SET_SELECTED_REGION: 'SET_SELECTED_REGION',
    SET_TV_LIST: 'SET_TV_LIST',
    SET_TV: 'SET_TV',
}
export default actionTypes;